const dashboardStyles = {
  container: {
    fontFamily: "Arial, sans-serif",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#f8f9fa",
    padding: "10px 20px",
    borderBottom: "1px solid #ddd",
    position: "sticky",       // <-- HEADER FIJO ARRIBA
    top: 0,
    zIndex: 50,
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontWeight: "bold",
    fontSize: "20px",
    color: "#333",
    cursor: "pointer",
  },
  searchBox: {
    flex: 1,
    margin: "0 40px",
  },
  searchInput: {
    width: "100%",
    padding: "8px 12px",
    border: "1px solid #ccc",
    borderRadius: "20px",
    outline: "none",
  },
  userSection: {
    display: "flex",
    alignItems: "center",
    position: "relative",
    cursor: "pointer",
  },
  userCircle: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#007bff",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    marginRight: "10px",
  },
  dropdown: {
    position: "absolute",
    top: "50px",
    right: 0,
    backgroundColor: "#fff",
    border: "1px solid #ddd",
    borderRadius: "5px",
    boxShadow: "0 2px 6px rgba(0,0,0,0.15)",
    padding: "10px",
    minWidth: "170px",
    zIndex: 100,
  },
  dropdownItem: {
    padding: "8px 10px",
    cursor: "pointer",
    borderRadius: "5px",
  },

  // main / layout
  main: {
    padding: "20px",
    overflowY: "auto",
    flex: 1,
    background: "#f5f7fb",
  },
  cardRow: {
    display: "flex",
    gap: "12px",
    marginBottom: "18px",
    flexWrap: "wrap",
  },
  card: {
    width: "200px",
    height: "140px",
    background: "#fff",
    borderRadius: "8px",
    boxShadow: "0 1px 6px rgba(0,0,0,0.08)",
    padding: "10px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    cursor: "pointer",
    position: "relative",
  },
  newCard: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  cardPreview: {
    fontSize: "32px",
    textAlign: "center",
  },
  cardTitle: {
    fontSize: "14px",
    color: "#333",
  },
  inviteButton: {
    position: "absolute",
    bottom: "10px",
    right: "10px",
    padding: "6px 8px",
    fontSize: "13px",
    borderRadius: "6px",
    border: "none",
    background: "#007bff",
    color: "#fff",
    cursor: "pointer",
  },

  // modal
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 200,
  },
  modal: {
    width: "420px",
    maxWidth: "95%",
    background: "#fff",
    borderRadius: "8px",
    padding: "18px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.2)",
  },

  // botón genérico dentro de modal
  button: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "none",
    background: "#007bff",
    color: "#fff",
    cursor: "pointer",
  },
  actionButtons: {
    display: "flex",
    gap: "6px",
    position: "absolute",
    bottom: "10px",
    right: "10px",
  },
  editButton: {
    padding: "4px 8px",
    fontSize: "16px",
    borderRadius: "4px",
    border: "none",
    background: "#28a745",
    cursor: "pointer",
  },
  deleteButton: {
   padding: "4px 8px",
    fontSize: "16px",
    borderRadius: "4px",
    border: "none",
    background: "#dc3545",
    cursor: "pointer",
  },
  inviteButton: {
    padding: "6px 8px",
    fontSize: "13px",
    borderRadius: "6px",
    border: "none",
    background: "#007bff",
    color: "#fff",
    cursor: "pointer",
  },
};
export default dashboardStyles;
